# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\"\x19\n\x03Row\x12\x12\n\npixel_temp\x18\x01 \x03(\x02\"\x9a\x01\n\nSensorData\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x0b\n\x03\x63o2\x18\x02 \x01(\x05\x12\x17\n\x0f\x62me_temperature\x18\x03 \x01(\x02\x12\x14\n\x0c\x62me_pressure\x18\x04 \x01(\x02\x12\x14\n\x0c\x62me_altitude\x18\x05 \x01(\x02\x12\x14\n\x0c\x62me_humidity\x18\x06 \x01(\x02\x12\x11\n\x03row\x18\x07 \x03(\x0b\x32\x04.Rowb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROW']._serialized_start=16
  _globals['_ROW']._serialized_end=41
  _globals['_SENSORDATA']._serialized_start=44
  _globals['_SENSORDATA']._serialized_end=198
# @@protoc_insertion_point(module_scope)
