repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.13.0'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: ["--exclude", "^(app/protobuf|rx.py)$", "--follow-imports", "skip"]
        additional_dependencies: ["types-protobuf", "types-PyYAML==6.0.12.20240917", "numpy==1.21.5"]
